"""
Conversation Controller - orchestrates multi-bot conversations.
Routes messages, manages turn-taking, and coordinates bot interactions.
"""

import logging
from typing import Dict, List, Optional

from gauntlet_lite.agents.bot_agent import BotAgent
from gauntlet_lite.models.conversation_state import ConversationContext
from gauntlet_lite.models.message import Message

logger = logging.getLogger(__name__)


class ConversationController:
    """
    Central orchestrator for multi-bot conversations.
    
    Responsibilities:
    - Register and manage multiple bots
    - Maintain shared conversation state
    - Route messages between bots
    - Coordinate turn-taking
    - Provide conversation flow control
    
    Attributes:
        bots: Dictionary mapping bot IDs to BotAgent instances
        context: Shared conversation context
        turn_order: List of bot IDs in turn order
        current_turn_index: Index of current bot in turn order
    """
    
    def __init__(self):
        self.bots: Dict[str, BotAgent] = {}
        self.context = ConversationContext()
        self.turn_order: List[str] = []
        self.current_turn_index = 0
    
    def register_bot(self, bot: BotAgent):
        """
        Register a bot with the controller.
        
        Args:
            bot: BotAgent instance to register
        """
        self.bots[bot.id] = bot
        self.turn_order.append(bot.id)
        logger.info(f"Registered bot: {bot.name} (ID: {bot.id})")
    
    def add_message(self, message: Message):
        """
        Add a message to the conversation (e.g., from a user).
        
        Args:
            message: Message to add to conversation
        """
        self.context.add_message(message)
        logger.info(f"Added message from {message.from_}: {message.content[:50]}...")
    
    def process_turn(self, bot_id: Optional[str] = None) -> Optional[Message]:
        """
        Process a single turn for a bot.
        
        Args:
            bot_id: Specific bot ID to process, or None for next in turn order
            
        Returns:
            Message generated by the bot, or None if no response
        """
        # Determine which bot's turn it is
        if bot_id:
            bot = self.bots.get(bot_id)
            if not bot:
                logger.error(f"Bot {bot_id} not found")
                return None
        else:
            # Round-robin turn order
            if not self.turn_order:
                logger.error("No bots registered")
                return None
            
            bot_id = self.turn_order[self.current_turn_index]
            bot = self.bots[bot_id]
            self.current_turn_index = (self.current_turn_index + 1) % len(self.turn_order)
        
        # Check if there's a message to respond to
        last_message = self.context.get_last_message()
        if not last_message:
            logger.info(f"No messages for {bot.name} to respond to")
            return None
        
        # Check if bot should respond
        if not bot.should_respond(last_message, self.context):
            logger.info(f"Bot {bot.name} chose not to respond")
            return None
        
        # Generate response
        logger.info(f"Bot {bot.name} generating response...")
        response = bot.respond(last_message, self.context)
        
        # Add response to context
        self.context.add_message(response)
        
        return response
    
    def run_conversation(self, initial_message: str, max_turns: int = 10, verbose: bool = True):
        """
        Run a complete conversation with all registered bots.
        
        Args:
            initial_message: Starting message to kick off conversation
            max_turns: Maximum number of bot turns to process
            verbose: Whether to print messages as they're generated
        """
        if not self.bots:
            logger.error("No bots registered")
            return
        
        # Add initial message
        initial_msg = Message(from_="user", content=initial_message)
        self.add_message(initial_msg)
        
        if verbose:
            print(f"\n{'='*60}")
            print("Starting Conversation")
            print(f"{'='*60}")
            print(f"{initial_msg}\n")
        
        # Process turns
        turn_count = 0
        no_response_count = 0
        while turn_count < max_turns:
            response = self.process_turn()
            
            if response:
                if verbose:
                    print(f"{response}\n")
                turn_count += 1
                no_response_count = 0  # Reset counter on successful response
            else:
                # No response generated, try next bot
                no_response_count += 1
            
            # Stop if we've cycled through all bots without any responses
            if no_response_count >= len(self.bots):
                logger.info("No bots responding after full cycle, ending conversation")
                break
        
        if verbose:
            print(f"{'='*60}")
            print(f"Conversation ended after {turn_count} turns")
            print(f"{'='*60}\n")
    
    def broadcast_message(self, content: str, from_: str = "system") -> List[Message]:
        """
        Broadcast a message and get responses from all bots.
        
        Args:
            content: Message content to broadcast
            from_: Sender ID (default: "system")
            
        Returns:
            List of response messages from bots
        """
        # Add broadcast message
        broadcast_msg = Message(from_=from_, content=content)
        self.add_message(broadcast_msg)
        
        responses = []
        for bot_id in self.turn_order:
            bot = self.bots[bot_id]
            if bot.should_respond(broadcast_msg, self.context):
                response = bot.respond(broadcast_msg, self.context)
                self.context.add_message(response)
                responses.append(response)
        
        return responses
    
    def get_conversation_summary(self) -> str:
        """
        Get a summary of the conversation so far.
        
        Returns:
            Formatted string with conversation history
        """
        summary_lines = [
            "="*60,
            "CONVERSATION SUMMARY",
            "="*60,
            f"Total messages: {len(self.context.messages)}",
            f"Participants: {', '.join(sorted(self.context.participants))}",
            "",
            "Message History:",
            "-"*60
        ]
        
        for msg in self.context.messages:
            summary_lines.append(f"[{msg.from_}]: {msg.content}")
        
        summary_lines.append("="*60)
        
        return "\n".join(summary_lines)
    
    def reset(self):
        """Reset the conversation state."""
        self.context.clear()
        self.current_turn_index = 0
        for bot in self.bots.values():
            bot.memory.clear()
        logger.info("Conversation reset")
    
    def __repr__(self):
        return f"ConversationController(bots={len(self.bots)}, messages={len(self.context)})"
