# Generated by Django 5.1.1 on 2024-10-06 13:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("model", models.CharField(max_length=255)),
                ("prompt", models.TextField()),
                ("temperature", models.FloatField(default=0.8)),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="New Conversation",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("title_update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LLMRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("request_type", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("temperature", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                ("total_tokens", models.IntegerField(default=0, editable=False)),
                ("completion_tokens", models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="Trigger",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CoreMemory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("memory", models.TextField()),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="core_memories",
                        to="chat.bot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "participant_type",
                    models.CharField(
                        choices=[("user", "User"), ("bot", "Bot")], max_length=10
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_bot",
                        to="chat.bot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
                (
                    "triggered_bots",
                    models.ManyToManyField(
                        blank=True, related_name="responded_messages", to="chat.bot"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="chat.participant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(
                related_name="conversations", to="chat.participant"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="triggers",
            field=models.ManyToManyField(
                blank=True, related_name="conversations", to="chat.trigger"
            ),
        ),
    ]
